Feature/tpbar
lucasvdiepen/VerticalSlice pull request #16
Opened 2021-12-08 13:08 UTC by BartdeBoer2001

2021-12-08 13:43 UTC, lucasvdiepen requested changes
Een aantal functies die nog geen access modifier hebben kunnen nog naar private.

Misschien is een apart Player object niet nodig buiten de prefab, maar gewoon het TP script op het TPBar object zetten

De TP bar begint met de kleur geel. Wanneer hij max is geweest en daarna weer lager wordt is hij pas oranje.
![TPBar_yellow_orange](https://user-images.githubusercontent.com/49072755/145218284-64b2025c-9348-4d0e-83dd-6d1d91c2d00c.gif)

2021-12-08 13:43 UTC, lucasvdiepen commented on VerticalSlice2D/Assets/Scripts/Player.cs
> +        if (TP > 100)
Dit zou niet elke frame moeten

2021-12-08 13:43 UTC, lucasvdiepen commented on VerticalSlice2D/Assets/Scripts/TPBar.cs
> +        Transform spriteMask = GameObject.Find("TPBar_Spritemask").GetComponent<Transform>();
Misschien kan dit ook via een SerializeField en dan slepen in de inspector

2021-12-08 13:43 UTC, lucasvdiepen commented on VerticalSlice2D/Assets/Scripts/TPBar.cs
> +        GameObject thePlayer = GameObject.Find("Player");
Alles wat je gebruikt van speler in een variabele opslaan. Dat zorgt ervoor dat player niet gezocht hoeft te worden elke frame.

2021-12-08 13:43 UTC, lucasvdiepen commented on VerticalSlice2D/Assets/Scripts/TPBar.cs
> +        GameObject thePlayer = GameObject.Find("Player");
Hier kun je dan ook de opslagen variabele gebruiken van speler

2021-12-08 13:43 UTC, lucasvdiepen commented on VerticalSlice2D/Assets/Scripts/TPBar.cs
> +        GameObject thePlayer = GameObject.Find("Player");
Hier kun je dan ook de variabele van speler gebruiken

2021-12-08 14:18 UTC, PiterGroot approved these changes

2021-12-08 14:38 UTC, lucasvdiepen requested changes
Prefab heeft nog unapplied changes.

Alle functies zonder access modifier zoals `Start()` kunnen nog naar private. Voorbeeld: `private void Start()`

Is het mogelijk om TP te gebruiken? anders misschien nog functies zoals `RemoveTP()` en `ResetTP()`

2021-12-08 14:38 UTC, lucasvdiepen commented on VerticalSlice2D/Assets/Scripts/TPBar.cs
> +        Transform spriteMask = GameObject.Find("TPBar_Spritemask").GetComponent<Transform>();
Hier kun je nu de `spriteMask` variabele gebruiken

2021-12-08 14:38 UTC, lucasvdiepen commented on VerticalSlice2D/Assets/Scripts/TPBar.cs
> +        UpdateTextAndTP();
Misschien deze functies alleen aanroepen wanneer de tp wordt aangepast zoals in `AddTP`

2021-12-08 14:38 UTC, lucasvdiepen commented on VerticalSlice2D/Assets/Scripts/TPBar.cs
> +        TP = TP + functionTP;
Hier misschien `TP += functionTP;`

2021-12-08 14:38 UTC, lucasvdiepen commented on VerticalSlice2D/Assets/Scripts/TPBar.cs
> +    public void AddTP(float functionTP)
Misschien de parameter naam veranderen naar `amount`

2021-12-09 08:50 UTC, lucasvdiepen requested changes
De prefab heeft nog unapplied changes.

En nog de access modifiers aanpassen naar private.

2021-12-09 08:50 UTC, lucasvdiepen commented on VerticalSlice2D/Assets/Scripts/TPBar.cs
> +    void Update()
Deze functie is niet meer nodig

2021-12-09 08:50 UTC, lucasvdiepen commented on VerticalSlice2D/Assets/Scripts/TPBar.cs
> +        UpdateTextAndTp();
Misschien moet de volgorde van deze functies andersom, want de tp kan nog aangepast worden nadat de sprite is aangepast.

2021-12-09 09:04 UTC, lucasvdiepen approved these changes

2021-12-09 09:05 UTC, merged